### ISSUE TITLE
Put reg info in speaker proposal form

### ISSUE THREAD

**Issue by suehle** [fedora-infra/flock-registration#10]
My recollection is that last year, we had to track down people who submitted talks but didn't register. Let's just put all of the registration information in the speaker form and simplify that. Is there a way to then combine that with the registration list, or would I have to manually separate people who did both?

**Comment by lmacken** [comment]
Since people can submit multiple presentation proposals, having the registration form combined with the proposal form might be confusing. I think the easiest solution might be to ensure that the person has registered before letting them submit a proposal.

**Comment by lmacken** [comment]
Done
