### ISSUE TITLE
I want to contribute to this app

### ISSUE THREAD

**Issue by rtnpro** [fedora-infra/flock-registration#25]
Hey,

I am a Fedora volunteer and an Ambassador. I am also a Python/Django developer. I want to help with developing this flock registration app. I just registered for Flock and I was not happy with various UI elements and I believe that this registration app can be improved a lot.

I am eager to help with this project. Please give me pointers on where to start from.

**Comment by lmacken** [comment]
I recommend starting by creating an OpenShift Python2.7 app with a MongoDB cartridge. You should then be able to copy the `wsgi/default_config.py` over to `wsgi/config.py`. Then after a `git push` the app should be up and running.

I'm open to any UI improvements :)
