### ISSUE TITLE
Hook up to new voting app

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/flock-registration#8]

**Comment by lmacken** [comment]
@pypingou are we able to import flock proposals into the new voting app at the moment? If not, I think we should probably use the old system since we need to start voting on them asap.

**Comment by pypingou** [comment]
I need to fix the login on stg so that we can test stg, eta tomorrow, afterward it all depends on the results of the tests I guess

**Comment by lmacken** [comment]
Okay, sounds good. I'll be off the grid headed to PyCon on Thursday, so we need to figure this out tomorrow :)

**Comment by pypingou** [comment]
roger that

**Comment by lmacken** [comment]
It also doesn't look like I am an elections admin, so I think either @pypingou or @abadger will need to import the flock proposals, which I just pasted here in the special voting format: http://fpaste.org/92692/90374139/

**Comment by pypingou** [comment]
I'm also not an election admin, maybe we can ask @nirik

**Comment by nirik** [comment]
Yeah, I am happy to try and help, but I have never imported anything before. ;)

**Comment by pypingou** [comment]
@lmacken what are the starting/ending dates?

**Comment by lmacken** [comment]
> @lmacken what are the starting/ending dates?

I just shot an email to Spot & Ruth about this…

**Comment by lmacken** [comment]
We want to start now and keep it open for 3 weeks.

**Comment by pypingou** [comment]
So say, April 10th, 2014 to May 1st? or May 2nd to make it a Friday

**Comment by lmacken** [comment]
works for me :shipit:

**Comment by nirik** [comment]
ok. It should be all ready to go at 00:00 on 2014-04-10...

**Comment by lmacken** [comment]
Excellent. I just updated the voting deadline and URL on https://register.flocktofedora.org

We should be good to go. Thanks guys!
